leonlatsch/Photok

app/src/main/res/values-es/strings.xml

Hi,
I have created translaions to spanish to Photok
Thanks

Create spanish translations

---

app/src/main/res/values-es/strings.xml

Hi,
I have updated the translations.

Update Spanish tranlations

---

app/src/main/java/dev/leonlatsch/photok/settings/Config.kt
app/src/main/java/dev/leonlatsch/photok/ui/components/BaseActivity.kt
app/src/main/java/dev/leonlatsch/photok/ui/start/SplashScreenViewModel.kt
app/src/main/java/dev/leonlatsch/photok/ui/start/onboarding/OnBoardingFragment.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoActivity.kt

Refactored config to be simpler to use

Refactoring: Config

---

app/build.gradle
app/src/main/java/dev/leonlatsch/photok/databinding/BindingConverters.kt
app/src/main/java/dev/leonlatsch/photok/model/database/dao/PhotoDao.kt
app/src/main/java/dev/leonlatsch/photok/model/database/entity/Photo.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
app/src/main/java/dev/leonlatsch/photok/ui/gallery/PhotoAdapter.kt
app/src/main/java/dev/leonlatsch/photok/ui/gallery/PhotoItemViewHolder.kt
app/src/main/java/dev/leonlatsch/photok/ui/process/ImportViewModel.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/DetailsBottomSheetDialog.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/PhotoPagerAdapter.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/PhotoViewHolder.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoActivity.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoViewModel.kt
app/src/main/res/layout/activity_view_photo.xml
app/src/main/res/layout/dialog_bottom_sheet_details.xml
app/src/main/res/layout/view_photo_item.xml

Implementing scrollable ViewPager for viewing photos.

Swipeable Photo Fullscreen

---

CONTRIBUTORS
app/src/main/res/values-pt-rBR/strings.xml

ptbr translation

---

CONTRIBUTORS
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/dev/leonlatsch/photok/other/Utils.kt
app/src/main/java/dev/leonlatsch/photok/ui/components/Dialogs.kt
app/src/main/java/dev/leonlatsch/photok/ui/settings/AboutFragment.kt
app/src/main/res/values/styles.xml
build.gradle

Migrate to official plugin for OSS licenses

---

app/src/main/res/values-zh-rCN/strings.xml

Update Chinese Strings

---

app/src/main/java/dev/leonlatsch/photok/ui/MainActivity.kt
app/src/main/java/dev/leonlatsch/photok/ui/viewphoto/ViewPhotoActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_view_photo.xml
app/src/main/res/layout/fragment_gallery.xml
app/src/main/res/layout/preference_layout_template.xml
app/src/main/res/values/styles.xml

Feature: New Toolbar

---

app/src/main/res/values-de/strings.xml

Update a single german string

---

app/src/main/assets/contributors.json

*update contributors json*
**Tasks:**

Add myself to contributors json

---

app/src/main/res/values-pt-rBR/strings.xml

updated strings in ptbr 
**Tasks:**

updated strings

---

app/build.gradle.kts
app/src/main/java/dev/leonlatsch/photok/model/io/PhotoStorage.kt

Fixes the thumbnail bug.
**Tasks:**

Video import crash issue resolved : Glide Lib Updated

---

app/src/main/res/values-pt-rBR/strings.xml

ptbr update

---

app/src/main/res/values-pt-rBR/strings.xml

Words replaced, photos to files

photos changed to files - ptbr

---

app/build.gradle.kts
app/src/main/java/dev/leonlatsch/photok/gallery/ui/PhotoAdapter.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/PhotoItemViewHolder.kt
app/src/main/res/layout/photo_item.xml

Updates room and paging lib to stable versions.
Also fixes bug with wrong displayed video icons.
**Tasks:**

Update room and paging

---

app/src/main/res/values-nl/strings.xml

Dutch Translation

---

fastlane/metadata/android/pt-BR/full_description.txt
fastlane/metadata/android/pt-BR/short_description.txt

ptbr descriptions

---

app/build.gradle.kts
app/src/main/assets/open_source_licenses.json
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

This PR updates all libs, Kotlin, Gradle, etc.
#170 
**Tasks:**

Library, Kotlin, Gradle Update

---

app/build.gradle.kts
app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryFragment.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryViewModel.kt
app/src/main/java/dev/leonlatsch/photok/news/newfeatures/ui/NewFeaturesDialog.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

Updates the news dialog to introduce the new recovery menu
**Tasks:**

Update News Dialog for 1.4.0

---

app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/SharedUrisStore.kt
app/src/main/java/dev/leonlatsch/photok/main/ui/MainActivity.kt
app/src/main/java/dev/leonlatsch/photok/main/ui/MainViewModel.kt

Fix Double Import from Sharing System

---

app/src/main/assets/contributors.json
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

- Add french translations
- Fix small typo in original `strings.xml`
**Tasks:**

Add french translations

---

app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/PhotoViewHolder.kt

Fixes #147 . Al least tries to :)
This seems to be a crash in the third party library
**Tasks:**

Fix Crash with big Photos

---

.idea/copyright/Leon_Latsch.xml
LICENSE
README.md
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Updates the copyright notice for 2023
**Tasks:**

Update Copyright for 2023

---

app/build.gradle.kts
build.gradle.kts

Update all dependencies
**Tasks:**

Update dependencies for all libraries and kotlin

---

app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryFragment.kt
app/src/main/res/layout/fragment_gallery.xml

Shows the amount of files in the safe.
**Tasks:**

show amount of files

---

app/src/main/java/dev/leonlatsch/photok/news/newfeatures/ui/NewFeaturesDialog.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Add #212 to the news dialog and increase the feature version code to show it on update
**Tasks:**

Update news dialog for 1.5.0

---

app/src/main/res/values-zh-rCN/strings.xml

Revert "Update Chinese Strings"

---

app/src/main/res/values-zh-rCN/strings.xml

Update Chinese Strings in Develop Branch Too

---

app/src/main/assets/contributors.json

added myself to maintainers
**Tasks:**

I guess i can't make changes directly to the main repo so i guess i need to make a pr

---

app/src/main/res/values-nl/strings.xml

Updated dutch translations
**Tasks:**

Update dutch translations

---

app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/GalleryContent.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/GalleryPlaceholder.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/PhotoGrid.kt
app/src/main/java/dev/leonlatsch/photok/main/ui/navigation/MainMenu.kt
app/src/main/java/dev/leonlatsch/photok/uicomponnets/compose/AppName.kt

Some tweaks for the new gallery:
**Tasks:**

Gallery Tweaks

---

app/src/main/java/dev/leonlatsch/photok/news/newfeatures/ui/NewFeaturesDialog.kt
app/src/main/java/dev/leonlatsch/photok/other/Utils.kt
app/src/main/java/dev/leonlatsch/photok/settings/ui/AboutFragment.kt
app/src/main/java/dev/leonlatsch/photok/settings/ui/SettingsFragment.kt
app/src/main/res/drawable/ic_money.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

- Add a settings entry for donating
- Cleanup openUrl usages
**Tasks:**

Settings Entry for donate button

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-pt-rBR/strings.xml

- add german translation for feature implemented in #259 
- add missing todo
**Tasks:**

Update german translation

---

app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryFragment.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryViewModel.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/GalleryPlaceholder.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/navigation/GalleryNavigationEvent.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/navigation/GalleryNavigator.kt
app/src/main/java/dev/leonlatsch/photok/news/newfeatures/ui/NewFeaturesDialog.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

- add strings for new features
- add display of dialog to new gallery
**Tasks:**

Update news dialog for next release and show it in new gallery

---

app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryFragment.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryUiState.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryUiStateFactory.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/GalleryViewModel.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/GalleryContent.kt
app/src/main/java/dev/leonlatsch/photok/cgallery/ui/compose/PhotoGrid.kt
app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt

- 3 columns in portrait
- 6 columns in landscape
**Tasks:**

Add changing column count in landscape mode

---

.github/dependabot.yml

Add group all to dependabot config

---

app/src/main/java/dev/leonlatsch/photok/backup/data/BackupLocalDataSource.kt
app/src/main/java/dev/leonlatsch/photok/backup/data/BackupMappers.kt
app/src/main/java/dev/leonlatsch/photok/backup/data/BackupMetaData.kt
app/src/main/java/dev/leonlatsch/photok/backup/data/BackupRepositoryImpl.kt
app/src/main/java/dev/leonlatsch/photok/backup/di/BackupModule.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/BackupRepository.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/CreateBackupMetaFileUseCase.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/DumpDatabaseUseCase.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/GetBackupRestoreStrategyUseCase.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupStrategy.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV1.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV2.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV3.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/ValidateBackupUseCase.kt
app/src/main/java/dev/leonlatsch/photok/backup/domain/model/BackupFileDetails.kt
app/src/main/java/dev/leonlatsch/photok/backup/ui/BackupViewModel.kt
app/src/main/java/dev/leonlatsch/photok/backup/ui/RestoreBackupViewModel.kt
app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/Mappers.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/data/AlbumRepositoryImpl.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/domain/AlbumRepository.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/domain/model/AlbumPhotoRef.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/AlbumsViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/AlbumPickerViewModel.kt
app/src/main/java/dev/leonlatsch/photok/model/database/PhotokDatabase.kt
app/src/main/java/dev/leonlatsch/photok/model/database/dao/AlbumDao.kt
app/src/main/java/dev/leonlatsch/photok/model/database/ref/AlbumPhotoRelation.kt
app/src/main/java/dev/leonlatsch/photok/other/Utils.kt

Include albums in backups / refactor backup code

---

app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailUiEvent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailUiState.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/compose/AlbumDetailContent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportBottomSheetDialogFragment.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportMenuDialog.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/importing/ImportViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/GalleryNavigationEvent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/GalleryNavigator.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/navigation/PhotoActionsNavigator.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

- adds some status messages
- Makes a import inside a album directly import into album
closed #304 
**Tasks:**

Album Feature Polish

---

app/src/main/java/dev/leonlatsch/photok/gallery/albums/data/AlbumRepositoryImpl.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailUiEvent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/AlbumDetailViewModel.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/compose/AlbumDetailScreen.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/domain/AlbumRepository.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/CreateAlbumDialog.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/RenameAlbumDialog.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/GalleryUiStateFactory.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
app/src/main/java/dev/leonlatsch/photok/model/database/dao/AlbumDao.kt
app/src/main/java/dev/leonlatsch/photok/settings/ui/SettingsViewModel.kt
app/src/main/res/drawable/ic_edit.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

- Missing feature: Delete albums and album refs when resetting photok
- Missing feature: Rename albums
- Some small code smells
**Tasks:**

Rename album & other missing features

---

app/build.gradle.kts
app/src/main/java/dev/leonlatsch/photok/gallery/albums/data/AlbumRepositoryImpl.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/domain/AlbumRepository.kt
app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImagePainter.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerFragment.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerViewModel.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/PhotoPagerAdapter.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/PhotoViewHolder.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/compose/PhotoItem.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/compose/PhotoViewHolderContent.kt
app/src/main/java/dev/leonlatsch/photok/model/database/dao/AlbumDao.kt
app/src/main/java/dev/leonlatsch/photok/model/database/dao/PhotoDao.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt
app/src/main/res/layout/view_photo_item.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Replaces the image viewer zooming library with a custom implementation in compose.
This library causes many crashes, especially with very big photos. See linked issues
closes #246 
fixes #203
**Tasks:**

Replace zoomable image library

---

app/build.gradle.kts
app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt

Implement playing gifs in the image viewer as it was before #317 
Closes #331

Implement playing gifs with coil

---

app/src/main/assets/contributors.json
app/src/main/res/values-ru/strings.xml

Just updated all the lines of Russian localization that were missing.

Update russian translations

---

app/src/main/AndroidManifest.xml

Allow install on external SD card. This is important as the library database can be massive.

Allow install on external SD

---

app/src/main/java/dev/leonlatsch/photok/backup/domain/RestoreBackupV1.kt
app/src/main/java/dev/leonlatsch/photok/di/AppModule.kt
app/src/main/java/dev/leonlatsch/photok/model/io/CreateThumbnailsUseCase.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt

- Refactores the changes done in #329 
- Changes thumbnail size to 256

Refactor thumbnail creation and increase size to 256

---

app/src/main/java/dev/leonlatsch/photok/model/database/entity/PhotoType.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt

I have tested on my phone and both the video and audio of webm files already work, this PR just allows importing them.
Fixes #206
**Tasks:**
n/a

allow importing webm video files

---

app/src/main/java/dev/leonlatsch/photok/imageloading/data/ImageStorageImpl.kt
app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
app/src/main/java/dev/leonlatsch/photok/imageloading/domain/ImageStorage.kt
app/src/main/java/dev/leonlatsch/photok/model/io/CreateThumbnailsUseCase.kt
app/src/main/java/dev/leonlatsch/photok/other/extensions/BitmapExtensions.kt

Fixes the size and aspect ratio of video previews.
Fixes #359 
**Tasks:**

[Bug] Fix Video Previews

---

.github/workflows/android.yml
.github/workflows/build-signed-release.yml

Update upload artifact action to v4

---

app/src/main/AndroidManifest.xml

Allow to backup app

---

app/build.gradle.kts

- Updates compile and target sdk to android 15

Support for Android 15

---

app/src/main/java/dev/leonlatsch/photok/model/database/entity/PhotoType.kt
app/src/main/java/dev/leonlatsch/photok/model/repositories/PhotoRepository.kt

Support for MOV videos.
Closes #390

[Feature] Support MOV Video Format

---

app/schemas/dev.leonlatsch.photok.model.database.PhotokDatabase/3.json
app/src/main/java/dev/leonlatsch/photok/model/database/PhotokDatabase.kt
app/src/main/java/dev/leonlatsch/photok/model/database/ref/AlbumPhotoRelation.kt

Set photo_uuid as index for album photo ref table.
Added DB Schema 3 with auto migration
Fixes #399

Improve album database performance

---

app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt

Fixes ANRs ins albums and image screen caused by new image loading introduced in #198

Fix: ANR in Albums and fully image screen.

---

app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/AlbumsContent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/compose/AlbumsPlaceholder.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryPlaceholder.kt
app/src/main/java/dev/leonlatsch/photok/ui/components/MagicFab.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Fixes the wrong label in gallery screen. It said "Import" since i recreated it with a text label.

Fix Label Magic Fab label for new album

---

app/src/main/java/dev/leonlatsch/photok/model/io/EncryptedStorageManager.kt

... by catching all exceptions and not just IO.

Fix: Crash when opening external file

---

app/src/main/java/dev/leonlatsch/photok/gallery/albums/ui/navigation/AlbumsNavigator.kt
app/src/main/java/dev/leonlatsch/photok/imageloading/compose/EncryptedImageFetcher.kt
app/src/main/java/dev/leonlatsch/photok/imageloading/di/ImageLoadingModule.kt
app/src/main/java/dev/leonlatsch/photok/setup/ui/SetupFragment.kt
app/src/main/java/dev/leonlatsch/photok/unlock/ui/UnlockFragment.kt
app/src/main/res/navigation/main_nav_graph.xml

Fix crashes and ANRs

---

app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/ImportMenuBottomSheet.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
app/src/main/java/dev/leonlatsch/photok/imageviewer/ui/ImageViewerFragment.kt
app/src/main/java/dev/leonlatsch/photok/other/extensions/Extensions.kt
app/src/main/java/dev/leonlatsch/photok/other/extensions/FragmentExtensions.kt
app/src/main/java/dev/leonlatsch/photok/settings/ui/SettingsFragment.kt

Fixes #444 
I forgot to re implement this when rewriting the import menu.

Fix: Auto Lock timer when choosing files and directories

---

app/src/main/res/values-zh-rCN/strings.xml

Update Simplified Chinese String

---

app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/MultiSelectionState.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt

Fix multiselection"Select All" when viewing album

---

app/src/main/java/dev/leonlatsch/photok/gallery/albums/detail/ui/compose/AlbumDetailContent.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/MultiSelectionState.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/components/PhotoGallery.kt
app/src/main/java/dev/leonlatsch/photok/gallery/ui/compose/GalleryContent.kt
app/src/main/java/dev/leonlatsch/photok/ui/components/MagicFab.kt
app/src/main/java/dev/leonlatsch/photok/ui/components/MultiSelectionMenu.kt
app/src/main/res/drawable/ic_check_circle.xml

This commit introduces a new visual style for selected items in the photo gallery during multi-selection mode.
Quite some fixes for the multi selection about
- animations
- shapes

Improvements for Multi Selection
